# Generated by Django 5.2.3 on 2025-06-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historia', '0002_historia_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Notas do autor')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do capítulo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='historia.historia')),
            ],
        ),
    ]
