# Generated by Django 5.2.3 on 2025-06-23 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopse', models.TextField(blank=True)),
                ('genero', models.IntegerField(choices=[(1, 'Fantasia'), (2, 'Ficção Científica'), (3, 'Romance'), (4, 'Mistério'), (5, 'Aventura'), (6, 'Drama'), (7, 'Terror'), (8, 'Comédia'), (9, 'Histórico')])),
                ('estilo', models.IntegerField(blank=True, choices=[(1, 'Narrativa em 1ª pessoa'), (2, 'Narrativa em 3ª pessoa'), (3, 'Diálogo puro'), (4, 'Crônica'), (5, 'Conto curto')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'Em andamento'), (2, 'Concluída'), (3, 'Pausada')], default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
