# Generated by Django 5.2.3 on 2025-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='historia/fotos'),
        ),
    ]
